# Generated by Django 5.0.6 on 2024-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adhar_number', models.CharField(max_length=12, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('assigned_mobile_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
