# Generated by Django 5.0.6 on 2024-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplan',
            name='existing_plan_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
