# Generated by Django 5.0.6 on 2024-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(choices=[(499, '499'), (299, '299'), (199, '199')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.IntegerField(choices=[(365, '365'), (180, '180'), (90, '90')]),
        ),
    ]
